server:
  port: 8111

spring:
  # springboot 内置的 Tomcat 默认上传文件大小为 1M, 低版本 springboot 将 servlet 改为 http
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 总文件大小(允许存储文件的文件夹大小)
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myself_lzc?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root#123QAZ!
#    url: jdbc:mysql://11.11.237.201:8066/cms?useUnicode=true&characterEncoding=UTF8&useSSL=FALSE&serverTimezone=Asia/Shanghai
#    username: sdp
#    password: lajsdhf*^KH@LJHljsdf
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置.
  # Maven 多模块项目的扫描路径需以 classpath*: 开头(即加载多个 jar 包下的 XML 文件)
  mapper-locations: classpath*:mybatis/mapper/*.xml
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 全局逻辑删除字段值
      logic-delete-field: is_delete
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 1
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 2
  configuration:
    # 是否开启自动驼峰命名规则映射, 数据库下划线命名列名到 Java 驼峰命名. 数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    map-underscore-to-camel-case: true
    # Mybatis一级缓存, 默认为 SESSION. 单服务开启可提高性能, 微服务需关闭, 因为同一个session相同查询语句不会再次查询数据库, 产生脏数据
    local-cache-scope: statement  # 关闭一级缓存
    # 开启Mybatis二级缓存, 默认为 true
    cache-enabled: false
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
